[package]
name = "practical_rust_book"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.32", features = ["full"] }
handle_errors = { path = "handle-errors" }
uuid = { version = "0.8", features = ["v4"] }
sqlx = {version = "0.7", features = [ "runtime-tokio-rustls", "postgres" ]}